apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: vault
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
  - name: vaultAddr
    value: "http://vault:8200"
  - name: vaultToken
    value: "root"
  - name: vaultEngine
    value: "secret"
auth:
  secretStore: vault
